---
- name: Folder in opt for repos
  become: true
  file:
    path={{ repo_path }}
    owner={{ server_user }}
    group={{ server_group }}
    mode=0755
    state=directory

- name: install zip
  apt:
    name=unzip
    state=present
  become: yes

- name: Remove libgnutls collisions
  apt:
    name=libgnutls-deb0-28
    state=absent
  become: yes
  
- name: Clone server for react
  git:
    repo={{ github_repo }}
    dest={{ repo_path }}/{{ github_repo | basename }}
    accept_hostkey=yes
    recursive=yes
    version={{ github_repo_version }}
    force={{ react_production }}
    update={{ react_production }}
  become: yes
  become_user: "{{ server_user }}"
  tags:
    - update_react_repo

- name: Install node dependencies
  command: "yarn --production"
  args:
    chdir: "{{ repo_path }}/{{ github_repo | basename }}"
  become: yes
  become_user: "{{ server_user }}"
  when: react_production
  tags:
    - update_react_repo

- name: Kill existing react services
  shell: "ps aux | grep node | grep -v grep | awk '{printf(\"%s \"), $2}' | xargs kill -9"
  become: yes
  become_user: "{{ server_user }}"
  tags:
    - kill_react
    - update_react_repo
    - update_services

- name: Start daemon production
  shell: "nohup {{ react_production_command }} 0<&- &> /tmp/reactpage.log &"
  args:
    chdir: "{{ repo_path }}/{{ github_repo | basename }}"
    executable: /bin/bash
  become: yes
  become_user: "{{ server_user }}"
  when: react_production
  tags:
    - update_react_repo
    - update_services
