---
- apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present
  become: yes
    
- apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    update_cache: yes
  become: yes

- name: Install yarn package
  apt:
    name: yarn
    state: present
    update_cache: no
  become: yes
